name: tikbox
description: TikTok comment reader with TTS

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1

  flutter_tts: ^4.0.2

  audioplayers: ^6.0.0

  shared_preferences: ^2.2.3

  wakelock_plus: ^1.2.5
  audio_service: ^0.18.15

  uuid: ^4.3.3
  collection: ^1.18.0
  web_socket_channel: ^3.0.3
  piratetok_live: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
